apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nimble-platform
    name: identity-service
  name: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nimble-platform
      name: identity-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: nimble-platform
        name: identity-service
    spec:
      containers:
      - image: nimbleplatform/identity-service:latest
        imagePullPolicy: Always
        name: identity-service
        ports:
        - containerPort: 9096
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: kubernetes
          - name: DISCOVERY_ENABLED
            value: "false"
          - name: DB_CREDENTIALS_JSON
            valueFrom:
              secretKeyRef:
                name: binding-nimble-identity-db-prod
                key: binding

---

kind: Service
metadata:
  name: identity-service
  labels:
    app: nimble-platform
    name: identity-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 9096
      targetPort: 9096
  selector:
    app: nimble-platform
    name: identity-service