apiVersion: v1
kind: Service
metadata:
  labels:
    app: identity-service
  name: identity-service
spec:
  selector:
    app: identity-service
  type: NodePort
  ports:
  - name: http
    port: 8080
    protocol: TCP
    nodePort: 30001
    targetPort: 9096